Repository maidsafe/safe-mobile-browser, pull requests merged in 2019-09, with the labels that each got.

#183 chore(Package): update MaidSafe.SafeApp package to v0.2.3
  SafeMobileBrowser/SafeMobileBrowser.Android/SafeMobileBrowser.Android.csproj
  SafeMobileBrowser/SafeMobileBrowser.iOS/SafeMobileBrowser.iOS.csproj
  SafeMobileBrowser/SafeMobileBrowser/SafeMobileBrowser.csproj
Labels: Code refactor/improvements

#185 fix (numeric url): load pages which have numeric public name and no service name
  SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
Labels: bug

#195 Xamarin UI Test Setup
  SafeMobileBrowser.UITests/AppInitializer.cs
  SafeMobileBrowser.UITests/SafeMobileBrowser.UITests.csproj
  SafeMobileBrowser.UITests/Tests.cs
  SafeMobileBrowser.sln
  SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/SafeMobileBrowser.iOS.csproj
  SafeMobileBrowser/SafeMobileBrowser/Views/MenuPopUp.xaml
Labels: UI Test

#196 Check if session is null when fetching the content and send correct error message title
  SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetchService.cs
Labels: bug

#197 UI Tests CI Setup and Basic Tests
  .gitignore
  CakeScripts/.gitignore
  CakeScripts/build.cake
  CakeScripts/build.ps1
  CakeScripts/build.sh
  CakeScripts/tools/packages.config
  SafeMobileBrowser.UITests/AppInitializer.cs
  SafeMobileBrowser.UITests/SafeMobileBrowser.UITests.csproj
  SafeMobileBrowser.UITests/SafeMobileBrowser.UITests.sln
  SafeMobileBrowser.UITests/Tests.cs
  SafeMobileBrowser.sln
  SafeMobileBrowser/SafeMobileBrowser.Android/Properties/AndroidManifest.xml
  SafeMobileBrowser/SafeMobileBrowser/SafeMobileBrowser.sln
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/MenuPopUp.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/SettingsModalPage.xaml
Labels: UI Test
