Repository maidsafe/safe-mobile-browser, pull requests merged in 2019-07, with the labels that each got.

#132 refactor/browser: refactor browser code using resharper
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/AdvancedProgressBarRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/CustomEntryRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewClient.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MainActivity.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/PlatformServices/PlatformService.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/SplashActivity.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/CustomUIProgressBar.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/SafeSchemaHandler.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/PlatformServices/PlatformService.cs
  SafeMobileBrowser/SafeMobileBrowser/App.xaml
  SafeMobileBrowser/SafeMobileBrowser/Controls/AddressBarEntry.cs
  SafeMobileBrowser/SafeMobileBrowser/Controls/AdvancedProgressBar.cs
  SafeMobileBrowser/SafeMobileBrowser/Controls/HybridWebView.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/ErrorConstants.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/Logger.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/RandomGenerators.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/RequestHelpers.cs
  SafeMobileBrowser/SafeMobileBrowser/Models/PopUpMenuItem.cs
  SafeMobileBrowser/SafeMobileBrowser/Models/TabPageStore.cs
  SafeMobileBrowser/SafeMobileBrowser/Services/AppService.cs
  SafeMobileBrowser/SafeMobileBrowser/Services/AuthenticationService.cs
  SafeMobileBrowser/SafeMobileBrowser/Services/BookmarkManager.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/AuthenticationPageViewMode.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/BaseViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/BookmarksModalPageViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/MenuPopUpViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/AuthenticationPage.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/BookmarksModalPage.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/BookmarksModalPage.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/MenuPopUp.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/SettingsModalPage.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/SettingsModalPage.xaml.cs
Labels: Code refactor/improvements

#140 Fix share Activity in iOS
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/MenuPopUpViewModel.cs
Labels: bug, iOS

#142 Feature: zooming in and out
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser/AssetFiles/index.html
Labels: enhancement

#145 feat/iOS: open safe url in browser
  SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/Info.plist
  SafeMobileBrowser/SafeMobileBrowser/App.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/MessageCenterConstants.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
Labels: iOS

#148 fix/iOS: check if the Sessions is not disconnected when fetching the web page
  SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetchService.cs
Labels: iOS
