Repository maidsafe/safe-mobile-browser, pull requests merged in 2019-08, with the labels that each got.

#153 fix(SafariViewController): Get rootviewcontroller to open links
  SafeMobileBrowser/SafeMobileBrowser.iOS/PlatformServices/PlatformService.cs
Labels: iOS

#162 remove authentication page and unnecessary default images
  SafeMobileBrowser/SafeMobileBrowser.iOS/Resources/Default-568h@2x.png
  SafeMobileBrowser/SafeMobileBrowser.iOS/Resources/Default-Portrait.png
  SafeMobileBrowser/SafeMobileBrowser.iOS/Resources/Default-Portrait@2x.png
  SafeMobileBrowser/SafeMobileBrowser.iOS/Resources/Default.png
  SafeMobileBrowser/SafeMobileBrowser.iOS/Resources/Default@2x.png
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/AuthenticationPageViewMode.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/AuthenticationPage.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/AuthenticationPage.xaml.cs
Labels: Code refactor/improvements

#156 chore(refactor): update hybridwebview to use commands
  SafeMobileBrowser/SafeMobileBrowser/Controls/HybridWebView.cs
  SafeMobileBrowser/SafeMobileBrowser/Services/AuthenticationService.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
Labels: Code refactor/improvements

#164 enable landscape mode in iOS
  SafeMobileBrowser/SafeMobileBrowser.iOS/Info.plist
Labels: enhancement

#165 chore(refactor): use Xamarin.Forms inbuilt zoom feature
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
Labels: Code refactor/improvements

#166 chore/license: update licensing to mention GPL3
  LICENSE
Labels: Documentation

#176 fix: bookmarks page 'no bookmarks text'
  SafeMobileBrowser/SafeMobileBrowser/Views/BookmarksModalPage.xaml
Labels: bug

#174 fix/browser: fix loading of numeric websites
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewClient.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/Constants.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
Labels: bug

#177 feat(swipe gesture) : enable back and forward navigation gestures on iOS
  SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/HybridWebViewRenderer.cs
Labels: enhancement, iOS

#178 chore(refactor): Code refactoring for uniformality
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/CustomEntryRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewChromeClient.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewClient.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MainActivity.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/PlatformServices/NativeThemeManager.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/CustomEntryRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/HybridWebViewRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/PlatformServices/NativeThemeManager.cs
  SafeMobileBrowser/SafeMobileBrowser.iOS/PlatformServices/PlatformService.cs
  SafeMobileBrowser/SafeMobileBrowser/Controls/ShadowBoxView.cs
  SafeMobileBrowser/SafeMobileBrowser/Converters/BytesToImageConverter.cs
  SafeMobileBrowser/SafeMobileBrowser/CustomAsyncCommand/AsyncCommand.cs
  SafeMobileBrowser/SafeMobileBrowser/CustomAsyncCommand/IAsyncCommand.cs
  SafeMobileBrowser/SafeMobileBrowser/CustomAsyncCommand/IErrorHandler.cs
  SafeMobileBrowser/SafeMobileBrowser/CustomAsyncCommand/TaskUtilities.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/FileHelper.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/Logger.cs
  SafeMobileBrowser/SafeMobileBrowser/Helpers/RequestHelpers.cs
  SafeMobileBrowser/SafeMobileBrowser/Models/TabPage.cs
  SafeMobileBrowser/SafeMobileBrowser/Models/TabPageStore.cs
  SafeMobileBrowser/SafeMobileBrowser/Services/Abstractions/ILoggingService.cs
  SafeMobileBrowser/SafeMobileBrowser/Services/BookmarkManager.cs
  SafeMobileBrowser/SafeMobileBrowser/Themes/DarkTheme.xaml
  SafeMobileBrowser/SafeMobileBrowser/Themes/LightTheme.xaml
  SafeMobileBrowser/SafeMobileBrowser/Themes/ThemeHelper.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/BaseViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/BookmarksModalPageViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/LogsModalPageViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/MenuPopUpViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/ViewModels/SettingsModalPageViewModel.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/BookmarksModalPage.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/MenuPopUp.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/Views/SettingsModalPage.xaml.cs
  SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
  SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetchConstants.cs
Labels: Code refactor/improvements

#179 docs(README): update README to include AppCenter links
  README.md
  docs/AppCenter-QR/android.png
  docs/AppCenter-QR/ios.png
Labels: Documentation

#170 Add image download context menu for Android
  SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MainActivity.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MediaDownload/DataImage.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MediaDownload/FileHelper.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MediaDownload/ImageDownloadMenuItemListener.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/MediaDownload/ImageDownloader.cs
  SafeMobileBrowser/SafeMobileBrowser.Android/Resources/drawable/notification_icon.png
  SafeMobileBrowser/SafeMobileBrowser.Android/SafeMobileBrowser.Android.csproj
Labels: Android
